# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-13 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20180714_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
