# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-14 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20180714_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
